#+title: Rust-Capr


A tool for specifiying sound law changes by compiling to finite state transducers similar to HFST and Foma. It is written in rust.

This was my master's thesis for the University of Tübingen. Even though I theoretically graduated in December, I still have not gotten my grade back 🙄


Try [[https://jzw2.github.io/rust-capr/][here]]. (Note, the online system is not working very well. Use the backend API calls and use cargo to run tests.)

* Installation

** Web user interface
You first need wasm-pack and cargo. Also you need yarn and parcel for the front end.
Run

=wasm-pack build --target web=

Then do =yarn run parcel index.html= to start a server.

** Just Backend

Make sure you have rust and cargo installed. It shouldn't need any external dependencies besides this.

To run the backend tests, use =cargo test= to run backend tests.


* Design

Most of the infastructure is built on top of the library =rustfst= which is largely openfst written in rust.
The replacement operator was surprisingly non trivial, and most code has been adapted from hfsts c++ implementation.
The rust creates a web assembly package which is then run in the browser.



* Similar projects

- https://zompist.com/sca2.html

- https://github.com/knightss27/capr
